### ISSUE TITLE
Naming of the method

### ISSUE THREAD

**Issue by harikt** [phly/phly_mustache#24]
This is regarding the naming of the method `setTemplatePath` and `addTemplatePath` as in comments

http://www.reddit.com/r/PHP/comments/xhy6t/phlymustache_templating_by_zf2chief_matthew_weier/

```php
public function setTemplatePath($path)
{
   if (!is_array($path))
       $path = array($path);
   $this->templatePath = $path;
}

public function addTemplatePath($path)
{
    $this->templatePath[] = $path; 
}
```

**Comment by weierophinney** [comment]
Closed with #33.
